version: 2.1
orbs:
    eslint: arrai/eslint@7.0.0
    prettier: arrai/prettier@5.0.0
    utils: arrai/utils@1.8.0
    npm: arrai/npm@2.2.0
    github: arrai/github@1.1.0
executors:
    node:
        environment:
            LANG: C.UTF-8
        docker:
            - image: cimg/node:16.15-browsers
workflows:
    test:
        jobs:
            - npm/coverage:
                  name: tests
                  context: arrai-global
                  filters:
                      branches:
                          only:
                              - main
            - npm/coverage:
                  name: tests-no-badge
                  context: arrai-global
                  create_badges: false
                  filters:
                      branches:
                          ignore:
                              - main
            - npm/publish:
                  name: publish
                  context: arrai-private-package-publishing
                  requires:
                      - tests-no-badge
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore: /.*/
            - github/create_release:
                  name: release_on_github
                  context: arrai-global
                  requires:
                      - tests-no-badge
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore: /.*/
    lint:
        jobs:
            - eslint/eslint:
                  name: eslint
                  context: arrai-global
                  files: "."
                  wd: "."
                  config:
                      - run:
                            name: NPM
                            command: |
                                sudo npm install -g --upgrade npm
                                npm ci
                  filters:
                      branches:
                          only:
                              - main
            - eslint/eslint:
                  name: eslint-no-badge
                  context: arrai-global
                  files: "."
                  wd: "."
                  config:
                      - run:
                            name: NPM
                            command: |
                                sudo npm install -g --upgrade npm
                                npm ci
                  create_badges: false
                  filters:
                      branches:
                          ignore:
                              - main
            - prettier/code_style:
                  name: prettier
                  context: arrai-global
                  executor: node
                  version: 2.6.2
                  filters:
                      branches:
                          only:
                              - main
            - prettier/code_style:
                  name: prettier-no-badge
                  context: arrai-global
                  executor: node
                  version: 2.6.2
                  create_badges: false
                  filters:
                      branches:
                          ignore:
                              - main
